services:
  postgres:
    image: postgres:16
    container_name: restaurant_postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - ./init_postgres_new.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d restaurant_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: restaurant_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./init_db_mongo_new.js:/docker-entrypoint-initdb.d/init.js:ro
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongo_data:

